server {
    # Vi sätter porten till 5173 direkt här istället!
    listen 5173;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Magin som löser 404-felet för alla /app/* routes
        try_files $uri $uri/ /index.html;
    }
}