image: node:24-alpine

stages:
  - test
  - docs
  - build
  - deploy

variables:
  PNPM_STORE_PATH: .pnpm-store
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/web
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/express

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - $PNPM_STORE_PATH

test_job:
  stage: test
  script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir $PNPM_STORE_PATH
    - pnpm install --frozen-lockfile
    - pnpm turbo run test
  rules:
    - changes:
      - apps/**/*
      - packages/**/*
      - pnpm-lock.yaml

build_documentation:
  stage: docs 
  script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir $PNPM_STORE_PATH
    - pnpm install --frozen-lockfile
    - echo "Syncing README-file..."
    - node scripts/sync-docs.mjs
    - pnpm --filter docs build
  artifacts:
    paths:
      - apps/docs/dist/
    expire_in: 1 week
  rules:
    - changes:
      - apps/docs/**/*
      - scripts/**/*
      - README.md

build_frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind  
  variables:
    DOCKER_HOST: tcp://docker:2375  
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $FRONTEND_IMAGE:latest -f apps/web/Dockerfile .
    - docker push $FRONTEND_IMAGE:latest
  rules:
    - changes:
      - apps/web/**/*
      - packages/**/*
      - pnpm-lock.yaml

build_backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind  
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $BACKEND_IMAGE:latest -f apps/express/Dockerfile .
    - docker push $BACKEND_IMAGE:latest
  rules:
    - changes:
      - apps/express/**/*
      - packages/**/*
      - pnpm-lock.yaml

deploy_to_k8s:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "$KUBECONFIG_DATA" > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
    
    - kubectl apply -f infrastructure/k8s/
    - kubectl rollout restart deployment backend-deployment -n doe25-group-4
    - kubectl rollout restart deployment frontend-deployment -n doe25-group-4
    - kubectl get pods -n doe25-group-4
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
