services:
  db:
    image: docker.io/library/postgres:18-alpine
    container_name: ccpilot_db
    environment:
      - POSTGRES_USER=ccpilot_admin
      - POSTGRES_PASSWORD=master_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./domain/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  postgres_data:
