apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: doe25-group-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: backend-container
          image: registry.chas-lab.dev/chas-challenge-2026/group-4/express:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-db-password
                  key: password
            - name: DB_USER
              value: "ccpilot_app"
            - name: DB_NAME
              value: "ccpilot_db"
            - name: DB_HOST
              value: "postgres-service"
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)?sslmode=disable"
            - name: SECRET_KEY
              value: "vi-vinnar-over-detta-nu-123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: doe25-group-4
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP