apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: doe25-group-4
data:
  POSTGRES_USER: "ccpilot_app"
  POSTGRES_DB: "ccpilot_db"
  PGDATA: "/var/lib/postgresql/data/pgdata"