apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: doe25-group-4
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: frontend-container
          image: registry.chas-lab.dev/chas-challenge-2026/group-4/frontend:latest
          ports:
            - name: http-web
              containerPort: 5173 
          resources: 
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: VITE_API_URL
              value: "http://backend-service:3000"
