apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: doe25-group-4-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: backend-container
          image: registry.chas-lab.dev/chas-challenge-2026/group-4/express:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-db-password
                  key: password
            - name: DB_USER
              value: "ccpilot_app"
            - name: DB_NAME
              value: "ccpilot_db"
            - name: DB_HOST
              value: "postgres-service"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            - name: BETTER_AUTH_URL
              value: "https://group4.cc.k3s.chas-lab.dev/api/auth"
            - name: TRUSTED_ORIGINS
              value: "https://group4.cc.k3s.chas-lab.dev"
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: BETTER_AUTH_SECRET
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)?sslmode=disable"
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY 
          envFrom:
            - secretRef:
                name: backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: doe25-group-4-prod
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP