apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: group4-ingress
  namespace: doe25-group-4-prod
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: doe25-group-4-api-rate-limit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: group4.cc.k3s.chas-lab.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service 
                port:
                  number: 80