---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-db-password
  namespace: doe25-group-4-prod
spec:
  encryptedData:
    password: AgCu3NG26y2vafP+Nm3+cGQOVeyOf+vW4YHtPRMD5KuoMegm+cccIl+Vg9kcDVlXU0eEJTPv7evzFLeaHqQNqx5YanbupO3fwshNVuWRIEOIr+C17rihkKZxGCPs22NOmM6ffPcaEPL2y45Tnpk8Z8qQ8aAx35bg+r2w/Mu2c24ykVWdNma+mCYqLOgqhShNyRs+2q27xMlFjmKcN2cIhQGQXtWAV8WIUfeydymEbtIjmeE5eOjn2mqtWAlljgtrv1yaDJ2ItJ5mCspggCcfQ3BrLDvjRTkz3Hd/5rHQ5Tpv2HXpaqg0idlh2avp3caEzk04Il+9CZjxEyIWJ/fTFHGGBFfTxONAS8AXFse4N7jh/+n/FRA1FMkF4hMqIDUtxx+a3ajxXgj6iWhiqRUmmW+JpYu9WDaRLcYk3ImRgtS9qNzK8cJFiZzZLYDlF5rcYMNviICnR3lpmWn3bZHf10itXviNX34u5chrkRSgSz+kgP39nxClS2Od1pzTctBe1PQtvduPogsE+T8Za2zHEyGkocXIzZjCYHRJNdn+9buIan1MuRcA0/wlKaoInxK0oEfcer0qTktpkcV8ITA6vJEI+7ar6h483ypS/IehGj7pQI62X50ZNDuCyLZwrVO3ku7WPEXZVC7NPqc/yn1lTaHXztf/yqeRWEF7eHw6rPEFtdmD9eQOLNprntTArOukmX+z679Qll3jjD26RHsMGoMYpXjwfLQQw+Kj/qBd6nv5U9g29A0g7xGx4abbZQ==
  template:
    metadata:
      creationTimestamp: null
      name: test-db-password
      namespace: doe25-group-4-prod
