---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-db-password
  namespace: doe25-group-4
spec:
  encryptedData:
    password: AgDUl2aw/SNQS82BGAf9kJiXy5t3GdanfgnsrWm1imlhuYQ9SjnWXerveNzK8mXa0nVUTo1DfaJ8lavXgjhBSi76DADKwktrtfN0sAU5HhAg7iGnlKXA3IjHZG+X6J39hnw9HiFiqyBtZBfLqNJkX1KxGOHkcTjH+UJHkyaOm+zwyKDgac7ID6SB8B3XK7w8yCLK/gkRtnR1gTXqshzQRDpP/IKXT3vhx74FU3bZOG56dxkxAfk7tGpm2GbBQ9jKCE4vVKSwBqIk5OGRamm9DHZlYu9fIrDlAjgllu4OfbVbCZlJlhDjePEYEdEnXckYoP/nH0l3a+097Cn0cez4Qq0oCVrcMbQK1V6dvOSHYE92Za2XvHdVXjrFjrGgsKfNW4aqperEKnmi/J2baXJMEbU2I8QYBS3Foepb2h+ZbVrWSW+DpjQx9jvNlXXhNry3IMPEiKVExNfB/I5gFfttGCFZ17u5Xjp5S51WuSx/zdP190t84rXzoFY9D/bucSslKC2AtjgoWoZy4cyWWkKHLacfXPsdEAeZQSv0e6Wb763vv9ys3A/k2sMXV+xC4EPBoesXLFIbH233sPrJvCDaDUHpgWzP/MfoB5+nG+rvjjJy+rwN3WEkStHTUOxx8Qe+Rv7XlQptY2iQn1I0cYHkTVzSh57OFxBk3PlHLNE4YCyc6oX34KABV/CMeiNWZtcSfgOoGH71KX9aX37iaAP/PD8o6iZ3A6jCAu8SF7vP/wNuVQvvwjUUsEo9njctKw==
  template:
    metadata:
      creationTimestamp: null
      name: test-db-password
      namespace: doe25-group-4
