/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRequirementsRouteImport } from './routes/app.requirements'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppNowRouteImport } from './routes/app.now'
import { Route as AppCockpitRouteImport } from './routes/app.cockpit'
import { Route as AppRequirementsIndexRouteImport } from './routes/app.requirements.index'
import { Route as AppStepIdRouteImport } from './routes/app.step.$id'
import { Route as AppSettingsUserRouteImport } from './routes/app.settings.user'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/app.settings.integrations'
import { Route as AppRequirementsIdRouteImport } from './routes/app.requirements.$id'
import { Route as AppGuidesCanvasRouteImport } from './routes/app.guides.canvas'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequirementsRoute = AppRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNowRoute = AppNowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => AppRoute,
} as any)
const AppCockpitRoute = AppCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AppRoute,
} as any)
const AppRequirementsIndexRoute = AppRequirementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRequirementsRoute,
} as any)
const AppStepIdRoute = AppStepIdRouteImport.update({
  id: '/step/$id',
  path: '/step/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUserRoute = AppSettingsUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppRequirementsIdRoute = AppRequirementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRequirementsRoute,
} as any)
const AppGuidesCanvasRoute = AppGuidesCanvasRouteImport.update({
  id: '/guides/canvas',
  path: '/guides/canvas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/cockpit': typeof AppCockpitRoute
  '/app/now': typeof AppNowRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/requirements': typeof AppRequirementsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/guides/canvas': typeof AppGuidesCanvasRoute
  '/app/requirements/$id': typeof AppRequirementsIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/user': typeof AppSettingsUserRoute
  '/app/step/$id': typeof AppStepIdRoute
  '/app/requirements/': typeof AppRequirementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/cockpit': typeof AppCockpitRoute
  '/app/now': typeof AppNowRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/guides/canvas': typeof AppGuidesCanvasRoute
  '/app/requirements/$id': typeof AppRequirementsIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/user': typeof AppSettingsUserRoute
  '/app/step/$id': typeof AppStepIdRoute
  '/app/requirements': typeof AppRequirementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/cockpit': typeof AppCockpitRoute
  '/app/now': typeof AppNowRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/requirements': typeof AppRequirementsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/guides/canvas': typeof AppGuidesCanvasRoute
  '/app/requirements/$id': typeof AppRequirementsIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/user': typeof AppSettingsUserRoute
  '/app/step/$id': typeof AppStepIdRoute
  '/app/requirements/': typeof AppRequirementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/cockpit'
    | '/app/now'
    | '/app/onboarding'
    | '/app/requirements'
    | '/app/settings'
    | '/app/guides/canvas'
    | '/app/requirements/$id'
    | '/app/settings/integrations'
    | '/app/settings/user'
    | '/app/step/$id'
    | '/app/requirements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/cockpit'
    | '/app/now'
    | '/app/onboarding'
    | '/app/settings'
    | '/app/guides/canvas'
    | '/app/requirements/$id'
    | '/app/settings/integrations'
    | '/app/settings/user'
    | '/app/step/$id'
    | '/app/requirements'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/cockpit'
    | '/app/now'
    | '/app/onboarding'
    | '/app/requirements'
    | '/app/settings'
    | '/app/guides/canvas'
    | '/app/requirements/$id'
    | '/app/settings/integrations'
    | '/app/settings/user'
    | '/app/step/$id'
    | '/app/requirements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requirements': {
      id: '/app/requirements'
      path: '/requirements'
      fullPath: '/app/requirements'
      preLoaderRoute: typeof AppRequirementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/now': {
      id: '/app/now'
      path: '/now'
      fullPath: '/app/now'
      preLoaderRoute: typeof AppNowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cockpit': {
      id: '/app/cockpit'
      path: '/cockpit'
      fullPath: '/app/cockpit'
      preLoaderRoute: typeof AppCockpitRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requirements/': {
      id: '/app/requirements/'
      path: '/'
      fullPath: '/app/requirements/'
      preLoaderRoute: typeof AppRequirementsIndexRouteImport
      parentRoute: typeof AppRequirementsRoute
    }
    '/app/step/$id': {
      id: '/app/step/$id'
      path: '/step/$id'
      fullPath: '/app/step/$id'
      preLoaderRoute: typeof AppStepIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/user': {
      id: '/app/settings/user'
      path: '/user'
      fullPath: '/app/settings/user'
      preLoaderRoute: typeof AppSettingsUserRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/integrations': {
      id: '/app/settings/integrations'
      path: '/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/requirements/$id': {
      id: '/app/requirements/$id'
      path: '/$id'
      fullPath: '/app/requirements/$id'
      preLoaderRoute: typeof AppRequirementsIdRouteImport
      parentRoute: typeof AppRequirementsRoute
    }
    '/app/guides/canvas': {
      id: '/app/guides/canvas'
      path: '/guides/canvas'
      fullPath: '/app/guides/canvas'
      preLoaderRoute: typeof AppGuidesCanvasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRequirementsRouteChildren {
  AppRequirementsIdRoute: typeof AppRequirementsIdRoute
  AppRequirementsIndexRoute: typeof AppRequirementsIndexRoute
}

const AppRequirementsRouteChildren: AppRequirementsRouteChildren = {
  AppRequirementsIdRoute: AppRequirementsIdRoute,
  AppRequirementsIndexRoute: AppRequirementsIndexRoute,
}

const AppRequirementsRouteWithChildren = AppRequirementsRoute._addFileChildren(
  AppRequirementsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsUserRoute: typeof AppSettingsUserRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsUserRoute: AppSettingsUserRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppCockpitRoute: typeof AppCockpitRoute
  AppNowRoute: typeof AppNowRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRequirementsRoute: typeof AppRequirementsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppGuidesCanvasRoute: typeof AppGuidesCanvasRoute
  AppStepIdRoute: typeof AppStepIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCockpitRoute: AppCockpitRoute,
  AppNowRoute: AppNowRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRequirementsRoute: AppRequirementsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppGuidesCanvasRoute: AppGuidesCanvasRoute,
  AppStepIdRoute: AppStepIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
