import { z } from "zod";
import { TokenProviderSchema } from "../integrations/definitions.ts";

//======================================================================
// Constants & Enums
// Defines the states and taxonomies for the Requirement domain
//======================================================================

export const RequirementTypeValues = [
  "assignment",
  "lecture",
  "message",
] as const;
export const RequirementTypeSchema = z.enum(RequirementTypeValues);
export type RequirementType = z.infer<typeof RequirementTypeSchema>;

export const RequirementSourceValues = ["canvas"] as const;
export const RequirementSourceSchema = z.enum(RequirementSourceValues);

/**
 * Status of the LLM Step Generation lifecycle.
 */
export const StepGenerationStatusValues = [
  "RAW",
  "GENERATING",
  "COMPLETE",
  "ERROR",
] as const;
export const StepGenerationStatusSchema = z.enum(StepGenerationStatusValues);
export type StepGenerationStatus = z.infer<typeof StepGenerationStatusSchema>;

/** Status of an external requirements sync process. */
export const SyncStatusValues = [
  "INITIALIZED",
  "IDLE",
  "PROCESSING",
  "COMPLETE",
  "ERROR",
] as const;
export const SyncStatusSchema = z.enum(SyncStatusValues);
export type SyncStatus = z.infer<typeof SyncStatusSchema>;

export const StepTypeValues = [
  "admin",
  "deepwork",
  "research",
  "planning",
  "polish",
  "decisions",
] as const;
export const StepTypeSchema = z.enum(StepTypeValues);
export type StepType = z.infer<typeof StepTypeSchema>;

//======================================================================
// Core Entities
// The primary objects used in our System
//======================================================================

/**
 * An atomic task generated by the LLM-Client.
 * These represent the NPF optimized steps of a requirement.
 */
export const StepSchema = z.object({
  id: z.uuid(),
  stepKey: z.string(),
  action: z.string(),
  complete: z.boolean().default(false),
  outcomeDefinition: z.string(),
  curiosityTrigger: z.string(),
  theWin: z.string(),
  category: StepTypeSchema,
  complexity: z.coerce.number(),
  estimatedMinutes: z.coerce.number(),
  dependencyOrder: z.coerce.number(),
  quickStartLinkHint: z.string(),
  requirementId: z.string(),
});
export type Step = z.infer<typeof StepSchema>;

/**
 * Our primary domain object.
 * Represents a high-level outcome for example a Canvas Assignment).
 */
export const RequirementSchema = z.object({
  id: z.string(),
  title: z.string(),
  url: z.string(),
  due: z.string(),
  type: RequirementTypeSchema,
  source: TokenProviderSchema,
  steps: z.array(StepSchema),
  status: StepGenerationStatusSchema,
  updatedAt: z.coerce.date(),
  integrationId: z.string().optional(),
  requirementSummary: z.string().optional(),
  externalId: z.string(), //ny
});
export type Requirement = z.infer<typeof RequirementSchema>;

//====================================================================
// Variations used for creating new entries or external communication.
//====================================================================

/** Used when creating a new step */
export const NewStepSchema = StepSchema.omit({
  id: true,
  requirementId: true,
});
export type NewStep = z.infer<typeof NewStepSchema>;

/** Used by the ef-engine */
export const ScoredStepSchema = StepSchema.extend({
  priorityScore: z.number(),
  effectiveDeadline: z.coerce.date(),
  requirementTitle: z.string(),
  requirementId: z.string(),
});
export type ScoredStep = z.infer<typeof ScoredStepSchema>;

/** Used when ingesting a new requirement from a sync source */
export const NewRequirementSchema = RequirementSchema.omit({
  id: true,
  status: true,
  updatedAt: true,
  requirementSummary: true,
});
export type NewRequirement = z.infer<typeof NewRequirementSchema>;

/** The shape expected from the LLM Step Generation prompt. */
export const StepsLLMResponseSchema = z.object({
  requirement_summary: z.string(),
  steps: z.array(NewStepSchema),
});
export type StepsLLMResponse = z.infer<typeof StepsLLMResponseSchema>;

/** Status feedback for the UI during sync operations. */
export const SyncStatusResponseSchema = z.object({
  status: SyncStatusSchema,
  stats: z.object({
    active: z.number(),
    total: z.number(),
  }),
});
export type SyncStatusResponse = z.infer<typeof SyncStatusResponseSchema>;
