#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

banner "Railway deployment for apps/express (issue #13)"
note "Target: apps/express deploying automatically from GitHub via Railway's native"
note "integration, wired to the Neon Postgres instance from issue #12, on a Railway URL"
note "that answers correctly. Nothing about your local Docker Postgres setup changes."

# ── Stage 1: create the Railway project and connect the GitHub repo ────────
stage "Railway: create the project and connect GitHub"
say "We're creating a brand-new Railway project and pointing it at this repo via"
say "Railway's GitHub App -- no railway.json, this is dashboard-configured."
open_url "https://railway.app/new"
step "Sign up or log in (GitHub OAuth is fastest)."
step "Choose 'Deploy from GitHub repo', install/authorize the Railway GitHub App if"
step "  prompted, and select this repo (AndreasJosef/agera)."
step "If Railway offers to add a railway.json / Config-as-Code file to the repo,"
step "  decline it -- dashboard settings only (Config-as-Code is being deprecated for"
step "  new services, hard cutoff 2026-12-01)."
step "Open the new service's Settings tab."
step "Under 'Source', set Root Directory to '/' (the repo root, not apps/express --"
step "  the Dockerfile's COPY paths assume a repo-root build context)."
step "Set Dockerfile Path to 'apps/express/Dockerfile'."
step "Under 'Networking', generate a public domain if one wasn't created automatically."
step "Under 'Deploy' (or the project/service settings), set the Region to"
step "  'EU West (Amsterdam)' -- closest to Neon's Frankfurt region."
step "Set the branch to deploy from to 'main', if not already the default."
step "Confirm auto-deploy is on: the service should redeploy on every push to 'main'"
step "  with no manual trigger (this is the GitHub App's default, but check the toggle"
step "  under Settings -> Source / Deploy Triggers)."
pause "Repo connected, Root Directory / Dockerfile Path / region / auto-deploy set?"

# ── Stage 2: set environment variables ──────────────────────────────────────
stage "Railway: set environment variables"
say "Railway has no CLI installed here, so these get pasted by hand into the"
say "service's Variables tab. Open it now (Service -> Variables -> New Variable /"
say "Raw Editor)."
note "PORT is provided by Railway automatically -- don't set it."
note "Note on naming: the ticket calls one of these 'SECRET_KEY', but the code"
note "(packages/crypto/src/crypto.ts) actually reads ENCRYPTION_KEY -- its own error"
note "message is just misnamed. Set the Railway variable as ENCRYPTION_KEY, not SECRET_KEY,"
note "or nothing will read it."

DB_URL=$(_existing RAILWAY_DATABASE_URL || _existing NEON_DATABASE_URL || true)
if [[ -z "$DB_URL" ]]; then
  warn "No Neon connection string found in $ENV_FILE yet -- run scripts/provision-neon.sh first."
  ask_secret RAILWAY_DATABASE_URL "Paste the Neon connection string to use as DATABASE_URL:"
  DB_URL="$RAILWAY_DATABASE_URL"
else
  note "Reusing the Neon connection string already saved in $ENV_FILE."
fi
say "Set in Railway:  DATABASE_URL=$DB_URL"
pause "Pasted DATABASE_URL into Railway?"
write_env RAILWAY_DATABASE_URL "$DB_URL"

ENCRYPTION_KEY=$(_existing RAILWAY_ENCRYPTION_KEY || true)
if [[ -z "$ENCRYPTION_KEY" ]]; then
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  say "Freshly generated (not reused from local dev):  ENCRYPTION_KEY=$ENCRYPTION_KEY"
else
  note "Reusing the ENCRYPTION_KEY generated on a previous run of this wizard."
  say "Set in Railway (if not already):  ENCRYPTION_KEY=$ENCRYPTION_KEY"
fi
pause "Pasted ENCRYPTION_KEY into Railway?"
write_env RAILWAY_ENCRYPTION_KEY "$ENCRYPTION_KEY"

BETTER_AUTH_SECRET=$(_existing RAILWAY_BETTER_AUTH_SECRET || true)
if [[ -z "$BETTER_AUTH_SECRET" ]]; then
  BETTER_AUTH_SECRET=$(openssl rand -hex 32)
  say "Freshly generated (not reused from local dev):  BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET"
else
  note "Reusing the BETTER_AUTH_SECRET generated on a previous run of this wizard."
  say "Set in Railway (if not already):  BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET"
fi
pause "Pasted BETTER_AUTH_SECRET into Railway?"
write_env RAILWAY_BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"

RAILWAY_OPENROUTER_API_KEY=$(_existing RAILWAY_OPENROUTER_API_KEY || true)
if [[ -z "$RAILWAY_OPENROUTER_API_KEY" ]]; then
  say "The ticket asks for a fresh secret here, not your local dev key -- mint a"
  say "separate production key so prod and local dev don't share one quota/limit."
  open_url "https://openrouter.ai/settings/keys"
  step "Create a new key (e.g. named 'agera-railway-prod')."
  if confirm "Created a dedicated production key on OpenRouter?"; then
    ask_secret RAILWAY_OPENROUTER_API_KEY "Paste the new production OpenRouter API key:"
  else
    warn "reusing your local dev OPENROUTER_API_KEY instead -- mint a dedicated one later."
    RAILWAY_OPENROUTER_API_KEY=$(_existing OPENROUTER_API_KEY || true)
    if [[ -z "$RAILWAY_OPENROUTER_API_KEY" ]]; then
      ask_secret RAILWAY_OPENROUTER_API_KEY "Paste the OpenRouter API key to use in production:"
    fi
    SKIPPED+=("Mint a dedicated production OpenRouter key (currently sharing the local dev key)")
  fi
else
  note "Reusing the production OpenRouter key generated on a previous run of this wizard."
fi
say "Set in Railway:  OPENROUTER_API_KEY=$RAILWAY_OPENROUTER_API_KEY"
pause "Pasted OPENROUTER_API_KEY into Railway?"
write_env RAILWAY_OPENROUTER_API_KEY "$RAILWAY_OPENROUTER_API_KEY"

# ── Stage 3: trigger the first deploy and capture the public URL ───────────
stage "Railway: deploy and capture the public URL"
say "Saving the variables in Stage 2 should already have triggered a deploy. If not,"
say "trigger one manually from the service's Deployments tab (Deploy / Redeploy)."
step "Watch the build logs until the deploy shows 'Success' / the service is Active."
step "Under Settings -> Networking, copy the public domain Railway assigned"
step "  (looks like https://<something>.up.railway.app)."
ask RAILWAY_URL "Paste the Railway public URL (including https://, no trailing slash):"
write_env RAILWAY_URL "$RAILWAY_URL"

# ── Stage 4: smoke-test the deployed backend against Neon ──────────────────
stage "Smoke-test the deployed backend"
say "Hits the deployed service's health endpoints directly -- /api/health confirms"
say "the process is up, /api/health/db confirms it can reach Neon."
if confirm "Ready to curl $RAILWAY_URL now?"; then
  if curl -fsS "$RAILWAY_URL/api/health" >/dev/null; then
    printf '  %s✓ /api/health OK%s\n' "$GREEN" "$RESET"
  else
    warn "/api/health did not return 200 -- check the Railway deploy logs."
    SKIPPED+=("Smoke test /api/health against $RAILWAY_URL -- re-run this script and press Enter to reuse the saved URL")
  fi
  if curl -fsS "$RAILWAY_URL/api/health/db" >/dev/null; then
    printf '  %s✓ /api/health/db OK -- backend reached Neon%s\n' "$GREEN" "$RESET"
  else
    warn "/api/health/db did not return 200 -- check DATABASE_URL in Railway's Variables"
    warn "tab, and that the Neon schema was pushed (scripts/provision-neon.sh, stage 3)."
    SKIPPED+=("Smoke test /api/health/db against $RAILWAY_URL -- re-run this script and press Enter to reuse the saved URL")
  fi
else
  SKIPPED+=("Smoke test $RAILWAY_URL/api/health and /api/health/db -- re-run this script and press Enter to reuse the saved URL")
  warn "skipped -- run the curl checks above by hand before closing out the ticket"
fi

finish
note "This script is a one-time provisioning aid -- safe to delete once Railway is"
note "confirmed working:"
note "  rm scripts/provision-railway.sh"
