#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

banner "Vercel deployment for apps/web (issue #14)"
note "Target: apps/web deploying automatically from GitHub via Vercel's native"
note "integration, zero-config, with a same-origin rewrite proxying /api/* to the"
note "Railway backend from issue #13 -- the fix that makes login work under Safari's"
note "cross-site cookie restrictions."
note ""
note "Contradicts ADR-0001 (retire k8s for managed hosting)'s stated tradeoff of"
note "accepting cross-origin frontend/backend traffic -- issue #11 refined that plan"
note "into this same-origin Vercel-rewrite design instead, since that's what's needed"
note "for Safari's ITP. Worth amending ADR-0001 to record the refinement."

RAILWAY_URL=$(_existing RAILWAY_URL || true)
if [[ -z "$RAILWAY_URL" ]]; then
  warn "No RAILWAY_URL found in $ENV_FILE -- run scripts/provision-railway.sh first."
  ask RAILWAY_URL "Paste the Railway public URL the proxy should point at:"
fi

# ── Stage 1: create the Vercel project and connect GitHub ──────────────────
stage "Vercel: create the project and connect GitHub"
say "We're importing this repo into a new Vercel project, scoped to apps/web."
open_url "https://vercel.com/new"
step "Sign up or log in (GitHub OAuth is fastest)."
step "Under 'Import Git Repository', install/authorize the Vercel GitHub App if"
step "  prompted, and select this repo (AndreasJosef/agera)."
step "On the 'Configure Project' screen, click Edit next to Root Directory and set"
step "  it to 'apps/web'."
step "Leave the Framework Preset on its auto-detected value (Vite) -- this deploy is"
step "  zero-config, so don't hand-edit Build/Output/Install commands."
note "apps/web/vercel.json is already committed to the repo -- it carries the"
note "/api/* rewrite to $RAILWAY_URL, the x-vercel-enable-rewrite-caching: 0 header"
note "on those paths, and ENABLE_EXPERIMENTAL_COREPACK=1 as an env var."
note "Nothing about those three needs pasting into the dashboard by hand."
step "Click Deploy."
step "Watch the build logs until the deploy finishes."
pause "Repo connected, Root Directory set to apps/web, deploy finished?"
step "Open the project's Settings -> Git tab and confirm 'Automatically expose System"
step "  Environment Variables' / PR preview deployments are on (this is Vercel's"
step "  default for a GitHub-connected project, but confirm rather than assume)."
if confirm "Preview deployments enabled for PRs?"; then
  note "PR previews confirmed -- these absorb the old staging environment's role"
  note "(issue #11, user story 3)."
else
  SKIPPED+=("Enable PR preview deployments in Vercel project Settings -> Git")
fi

# ── Stage 2: capture the URL and check what the build actually did ─────────
stage "Vercel: capture the URL and check the build log"
say "Two things to confirm from the build log before moving on."
step "In the build log, find the Corepack line and confirm it installed/used"
step "  pnpm 10.33.0 (the version pinned in package.json's packageManager field) --"
step "  not whatever pnpm Vercel's image ships by default."
if confirm "Corepack honored the pinned pnpm 10.33.0?"; then
  note "good -- ENABLE_EXPERIMENTAL_COREPACK=1 is doing its job."
else
  warn "Corepack didn't honor the pin -- double check the env var landed"
  warn "(Project Settings -> Environment Variables, or that vercel.json's"
  warn "top-level env block made it into the deployed commit)."
  SKIPPED+=("Corepack not honoring pinned pnpm 10.33.0 -- investigate before closing out #14")
fi
step "Still in the build log, search for 'storybook build' and check whether"
step "  @ccpilot/ui's storybook step ran as part of this build (turbo's"
step "  dependsOn: [\"^build\"] may be pulling it in transitively)."
if confirm "Did storybook build get pulled into the apps/web build?"; then
  VERCEL_STORYBOOK_PULLED_IN=yes
  note "recorded -- issue #16 needs this before it can decide whether"
  note "apps/web/Dockerfile + nginx.conf are safe to delete."
else
  VERCEL_STORYBOOK_PULLED_IN=no
fi
write_env VERCEL_STORYBOOK_PULLED_IN "$VERCEL_STORYBOOK_PULLED_IN"
step "Open the deployment's overview page and copy its production domain"
step "  (looks like https://<something>.vercel.app)."
ask VERCEL_URL "Paste the Vercel production URL (including https://, no trailing slash):"
write_env VERCEL_URL "$VERCEL_URL"

# ── Stage 3: trust the new origin on Railway ────────────────────────────────
stage "Railway: trust the new Vercel origin"
say "The browser now only ever talks to $VERCEL_URL -- Vercel's rewrite forwards"
say "the request to Railway server-side. better-auth's own origin/CSRF checks"
say "(packages/auth-betterauth/src/better-auth-config.ts) still need to trust that"
say "public origin, and its baseURL should point at it too so any absolute links"
say "it generates (e.g. password-reset emails) point at the public domain, not the"
say "internal Railway URL."
note "No cookie-config change needed: better-auth-config.ts already leaves sameSite"
note "at its default (only secureCookies/cookiePrefix vary by NODE_ENV) -- that"
note "criterion is satisfied as-is, now that same-origin makes 'none' unnecessary."
open_url "https://railway.app/dashboard"
step "Open the apps/express service -> Variables tab."
step "Set TRUSTED_ORIGINS to: $VERCEL_URL"
step "Set BETTER_AUTH_URL to: $VERCEL_URL/api/auth"
pause "Both variables pasted into Railway?"
write_env TRUSTED_ORIGINS "$VERCEL_URL"
write_env BETTER_AUTH_URL "$VERCEL_URL/api/auth"
note "Saving these triggers a Railway redeploy -- wait for it to finish (Deployments"
note "tab shows Active) before the smoke test in the next stage."
pause "Railway redeploy finished (service Active)?"

# ── Stage 4: smoke-test the proxy and login end-to-end ──────────────────────
stage "Smoke-test the proxy, then log in through it"
say "First confirms the rewrite reaches Railway (and Railway reaches Neon);"
say "then a manual login pass in both browser families the ticket cares about."
if confirm "Ready to curl $VERCEL_URL now?"; then
  if curl -fsS "$VERCEL_URL/api/health" >/dev/null; then
    printf '  %s✓ /api/health OK through the Vercel proxy%s\n' "$GREEN" "$RESET"
  else
    warn "/api/health did not return 200 through the proxy -- check the rewrite in"
    warn "apps/web/vercel.json and that $RAILWAY_URL is still the correct Railway URL."
    SKIPPED+=("Smoke test /api/health through $VERCEL_URL")
  fi
  if curl -fsS "$VERCEL_URL/api/health/db" >/dev/null; then
    printf '  %s✓ /api/health/db OK -- proxy reaches Railway reaches Neon%s\n' "$GREEN" "$RESET"
  else
    warn "/api/health/db did not return 200 -- check Railway's DATABASE_URL and logs."
    SKIPPED+=("Smoke test /api/health/db through $VERCEL_URL")
  fi
else
  SKIPPED+=("Smoke test $VERCEL_URL/api/health and /api/health/db")
  warn "skipped -- run the curl checks above by hand before closing out the ticket"
fi

say "Now the actual point of #14: log in end-to-end at $VERCEL_URL, once in a"
say "Chromium/Firefox-family browser and once in Safari specifically -- Safari's"
say "ITP is what silently broke cross-site cookies on the old two-origin setup."
open_url "$VERCEL_URL"
step "Log in (or sign up, then log in) in Chrome or Firefox."
if confirm "Login worked end-to-end in Chrome/Firefox?"; then
  note "Chrome/Firefox login confirmed."
else
  SKIPPED+=("Login in Chrome/Firefox at $VERCEL_URL")
fi
step "Repeat the same login in Safari."
if confirm "Login worked end-to-end in Safari?"; then
  note "Safari login confirmed -- this is the retirement signal #16 needs (a)."
else
  SKIPPED+=("Login in Safari at $VERCEL_URL -- this blocks #16's retirement signal (a)")
fi

finish
note "This script is a one-time provisioning aid -- safe to delete once Vercel is"
note "confirmed working:"
note "  rm scripts/provision-vercel.sh"
