#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

banner "Neon Postgres provisioning (issue #12)"
note "Target: a fresh, empty Neon project (free tier, eu-central-1/Frankfurt),"
note "schema pushed, and a verified write/read round-trip. Your local Docker"
note "Postgres (.env's DATABASE_URL) is left untouched throughout."

# ── Stage 1: create the Neon project ───────────────────────────────────────
stage "Neon: create the project"
say "We're creating a brand-new Neon project -- no data migrates from the old cluster."
open_url "https://console.neon.tech"
step "Sign up or log in (GitHub OAuth is fastest; free tier needs no card)."
step "Click 'New Project' (or 'Create a project')."
step "Postgres version: leave the default."
step "Project name: e.g. 'agera'."
step "Region: choose 'AWS Europe (Frankfurt) -- eu-central-1'."
step "Plan: leave it on Free (that's the default for a new project; no need to pick a paid tier)."
step "Click Create. Neon generates a fresh database, role, and password for you -- don't reuse the old cluster's sealed-secret password anywhere."
pause "Project created?"

# ── Stage 2: copy the direct connection string ─────────────────────────────
stage "Neon: copy the direct connection string"
say "The new project's dashboard shows a 'Connection Details' panel (or Dashboard -> Connect)."
step "Database: neondb. Role: the default owner role (e.g. neondb_owner)."
step "Turn OFF any 'Pooled connection' / 'Connection pooling' toggle -- we want the direct endpoint."
note "Why direct: apps/express runs as a long-lived container holding a small pg.Pool, not"
note "high-churn serverless calls, and Neon's own docs recommend the direct endpoint (not the"
note "PgBouncer pooler) for that shape of workload."
step "Copy the full connection string (starts postgresql://, ends ?sslmode=require)."
ask_secret NEON_DATABASE_URL "Paste the Neon connection string:"
write_env NEON_DATABASE_URL "$NEON_DATABASE_URL"
note "Saved as NEON_DATABASE_URL, separate from DATABASE_URL -- local dev keeps using Docker."
note "Keep this value somewhere durable (password manager); you'll reuse it as Railway's"
note "DATABASE_URL when that service is wired up in a later ticket."

# ── Stage 3: push the schema ────────────────────────────────────────────────
stage "Apply schema to Neon"
say "Runs drizzle-kit push with DATABASE_URL pointed at Neon for this one command only."
warn "drizzle-kit will likely ask you to confirm the schema diff interactively -- answer yes."
if confirm "Ready to run 'pnpm --filter @ccpilot/persistence db:push' against Neon now?"; then
  if ( cd "$REPO_ROOT" && DATABASE_URL="$NEON_DATABASE_URL" pnpm --filter @ccpilot/persistence db:push ); then
    printf '  %s✓ schema pushed%s\n' "$GREEN" "$RESET"
  else
    warn "db:push failed -- see the error above."
    SKIPPED+=("pnpm --filter @ccpilot/persistence db:push against Neon (DATABASE_URL=\"\$NEON_DATABASE_URL\")")
  fi
else
  SKIPPED+=("pnpm --filter @ccpilot/persistence db:push against Neon (DATABASE_URL=\"\$NEON_DATABASE_URL\")")
  warn "skipped -- run that before the round-trip check below, or it will fail"
fi

# ── Stage 4: verify a write/read round-trip ─────────────────────────────────
stage "Verify a write/read round-trip against Neon"
say "Writes a throwaway row via the same Drizzle + pg.Pool client apps/express uses,"
say "reads it back, then deletes it -- Neon stays schema-only afterward."
ROUNDTRIP_FILE="$REPO_ROOT/apps/express/.neon-roundtrip-check.mjs"
cat > "$ROUNDTRIP_FILE" <<'JS'
import { pool, db, user } from "@ccpilot/persistence";
import { eq } from "drizzle-orm";

const marker = `neon-roundtrip-${Date.now()}`;
const row = {
  id: marker,
  name: "Neon round-trip check",
  email: `${marker}@example.invalid`,
  emailVerified: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

try {
  await db.insert(user).values(row);
  const [readBack] = await db.select().from(user).where(eq(user.id, marker));
  if (!readBack || readBack.email !== row.email) {
    throw new Error("round-trip mismatch: row read back did not match what was written");
  }
  await db.delete(user).where(eq(user.id, marker));
  console.log("Neon round-trip OK:", readBack.email);
} finally {
  await pool.end();
}
JS

if ( cd "$REPO_ROOT/apps/express" && DATABASE_URL="$NEON_DATABASE_URL" node "$ROUNDTRIP_FILE" ); then
  rm -f "$ROUNDTRIP_FILE"
  printf '  %s✓ round-trip verified -- Neon is schema-only again%s\n' "$GREEN" "$RESET"
else
  warn "round-trip failed -- see the error above. Common causes: schema not pushed yet,"
  warn "wrong connection string, or Neon's compute still waking from scale-to-zero (retry once)."
  SKIPPED+=("Neon round-trip check: DATABASE_URL=\"\$NEON_DATABASE_URL\" node $ROUNDTRIP_FILE (run from apps/express)")
fi

finish
note "Supabase-as-fallback is documented in packages/persistence/README.md."
note "This script is a one-time provisioning aid -- safe to delete once Neon is confirmed working:"
note "  rm scripts/provision-neon.sh"
