---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry-secret
  namespace: doe25-group-4
spec:
  encryptedData:
    .dockerconfigjson: AgAY9WsoBZiQ61TCzdceEkAioDhzo4ju7ONNZfVquk6emqudjPm5+4Edc+574l/pAJrz9vUFZHM06WCwhIWkNZtjRj26eAHHPoxy8Qkk9pIIiaHWB8G4e9b9D/lnuSFkruQc0cvRgs7cQiVMnGUUoXKyMOsYhNkBsHDZ1xy52TI51r3nTFMeZj/TcCS1XSFaYdNDp68KPmZ+s9FN3PBiTYF8BbCWZwZ4n2xdpf9sb56QOPJXhYLh/9fTw24NbK+PxfhqRen+yIzAiJj+exLxomxCIIHKLs9lP71CKx8iVFYsJ1uO8AizifI6V5fIk6hW68Q4FlK2goxfsHGs8XIDbPLDpovH1gFz7CPP1+wD2U2O88NxXDNTk9Fz+Q7r4SJsIlP+FHV7nCC4dad/fjDr4JK3iNf6kaExy1Rf9hBEXb8qZPYIzkcFmimGi++JLpOaNZ8jvepYrr34KvBmYnC33jrnNy8Qo+hbAa7qBs/Ifb7RFzuy/C8HrqhyB3GuTxNgjf19xKiogyF7DzEyqap4FrgZbLKLyB8s7950m9s57GwC2J8IjkXIo8sdNRZtkq9dGTRm8Xwe7uawI3Jyxj5bmgJTf8s/Xg4W20vdWgwxZExDYKo7AwJHUCXGyBrOLtb3dCNUSBfpZn50ap9NHfC3Br0nOISELMtoSPbEGKs/QqXAiBQPpRFp1PhncFLQPE5ScV4PnScTONpqKl5Ro/ESFktkw83e23oTESG1vvcvct2TesZGx+lR0mKIuReeLnIcSN9zkF8MD+4ImHicwuZo990G6eQmi3U9bF/CRG4ehND64wgJ7ldAtbvWjMx1AxEhT9SCZ7eZh1DjhluTBvkWSk3rvW4KFC13PqymnfC6sAD61lRomhn4phI=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry-secret
      namespace: doe25-group-4
    type: kubernetes.io/dockerconfigjson
