---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-db-password
  namespace: doe25-group-4
spec:
  encryptedData:
    password: AgAl2ed1hKSnZAWtQlrvUbHGyEmdo4s4oxkfmHSjsulT0y6IP/EcPEhGIssNfb1+wPdizeJCNyJOJQy2V5qva9Wdzy42lbe7dFTepemDa0vS4X14o0X+oRqRZUpwkHTFE5T3KP8GkohqtlV4lSwlgpPGkWvN2LG7nOFxJmTw4kK8ku7T2YmMZ2w+7CzefHy5J0nEo5P7xyklpGEG3Xo+udZ+42fvWfLifbpcYyw2002B3ybFoCLGGxwaX8mOe0hQ1eCNgME6oExfoXy2FIK3KqmnRD4aXsr7joQRqLIH1f7Ux1qZxhxsc3kf9IeEVIwtg58pDzK4YJceI2Eizn3NBXqAJ9+Fy8kmDg9CUNE97JKTTGNHw9cL9T3wWszltI8XhTUyWcUq0J2JQVJre5TBaGHeXi0rUM4igvg76aOw0UAuNZcc6DRsS9j2+EyzLsuDGbWYpFaCHJHJ0zaoxwe8K4eJawidc+ggOm2aeflSlz9qFtysMOyuN3CjlNhisx/arcTwqhdiguqHSn+CM2HnkaG7s7R8YqpzGXr5GJUF6iI4MgsyUFQKYwaM4N9dpJhd/dIatbKdh9fdmcp8srbbtsBfjohd/Us9ruuPP/VMldKSafMg1N8tXln2SvlkKZWw2ODcL9Zp38XPv6R5RnQek/F2oOdbgNISenJuEmL+NsVM9GFYtm18WlhIQ2fnQ5bn7eSr+jTikEndGzjIDOuy+GA=
  template:
    metadata:
      creationTimestamp: null
      name: test-db-password
      namespace: doe25-group-4
