---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secrets
  namespace: doe25-group-4
spec:
  encryptedData:
    ENCRYPTION_KEY: AgABun2Jv2O2QxysQiKgghIGeFh615bEV0CvslQsnM4ks+Wl+N/2LBwXVFeP//F0zeD4KltrIlub5LNhKtOeB2MQRlzxMcT4t/D+glYFTdtdtj9pxnQKIRKY8WFitR+eQDGB646HUSWf3ZXHJYOv5CsIVwtkTbBxFAcbJjag3jAHgIoe4oWDdHsTH+b8BvtBur4EY6wS+9hwyqtIV+H86ejr2XGomGD+Mlen31rc5bZGhbG2YtQYDmDIcrmJFdrrnWNrENy7eqKtFo4+jZ1peLfIVPAceEjk6otUPNknzXx9e/NhJaCtD0hV54hCDmvCN34qrqofC+EWiV3KiwZW25DhrZswKOt+M85Mn8FqadsVSXUwz4461N5m6PpzH2g4PoVbqT/LS5/v7gCnxYBS81b8MQ3MdnwCq3KvFDYbrv7/UWR8NGb8z/Eu9JTgj3G2B1HC+wMIlpNYuOyoTpWxTh0rUVsP5CVsTeZFB4J98XVglKqa2lq1FddtNLjx6MqreGyZvOMEO/4Aaln2VO5nrv7xyDShgAXuxhjsA9Vr0TD6TBMIwsJYWumw+3ub60ykUo127uW6smrOx0wjkvqjkonYbuZX9SLz34rPP9DLG7UYSySUNM8nmQUdcbXJ1cSiiZU4SEN6g6lveefrOkhYnaizQB3TpgBpL5JuDfs6M3uy3mMZ/qoGXatxXTvnRmSe4SDCkCLdE888N47Ii2jN+UM4FRAMKLYePa7H
  template:
    metadata:
      creationTimestamp: null
      name: backend-secrets
      namespace: doe25-group-4
