---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry-secret
  namespace: doe25-group-4
spec:
  encryptedData:
    .dockerconfigjson: AgCrjjy0qhlEsf/Kk90tH/nCdyZWsDi3BSZShtwBVQuut/a3WP5O68z57kfjVcBHIP5mwO03oatiypsnDxgUxLfzto+WPAS868qa2+9pczLv4QTGp7WtnevcTLUfJLITrF3IXLiLNwA47uS4cheWJC+Cn9ALeIXsGfWagGbuzV4mSUE/LTXdOGgIijyl7DUt0jXDBclbt/53zgM4emvJUO8+zqtIjWuxcFa+E1xqay5dXqrMudhxIB5FGBEXxK6yuQBkbSChtum8eA9hgO5B8At3ZbmTz3G/Rmo+brHbqjc60Lwgi6abfyzmp3a/ccHzp9jyQvcZqOBQdcDdt16573ZfDzgDv8m5ngOu6eRo5gZKCiaYUf8TYDSxZ26wPVED0wpBd2FpOQzQxMVfyrhcuvlGurTXDjhbxtlhT0VPepnxtUPVZj6+Ay1G30cX5hF4aOb/jS3XGA5UNxfgqvwxRe+KFX8JXNIctqATGfYIeqXfFezY+jWPsv7ZBtpwkGl8Vs9rqToYk3P9xe0P23AjavbnkZYPsLYiUacFeR9VECSKb6fGjJ8XpBa66d4i0YyVlCU9djmmxVwTGtDYjDLHszuKTOLN2HHTM/SyD7f8Quc/SxxB6x5LVd2/7FQD9VffM2zQDi0eHYYHGllDRCmL2tW60J2dlughss0je1Ma4QeLhzkvXCnWypbA1Mf0ANAWXoE5pbUGDQAw2b099j0UJf7t40uNlvbhM4z61W6n3Uhd+63KlNrugnYFsFmVMxOKZ1G3/MULR36IC7xnm/6/TNelMyhT2cMfjhMzi27JTfdJmLVE+QzKYcKp6N4ErjC+vUc7eZCEgDSrQm3guVM+/wMLeoKASpAHpZDLDSYsKIrNK+BYZo5Ua6net+Qcz4k=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry-secret
      namespace: doe25-group-4
    type: kubernetes.io/dockerconfigjson
